version: "3"

services:
  mongodb-auth:
    image: mongo:4.2.5
    container_name: mongodb
    restart: always
    ports:
      - '27018:27017'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb-auth
    container_name: app
    volumes:
      - ./api:/app/api
    command: bash -c "cd api && uvicorn routers:app --reload"
    ports:
      - 8000:8000
    # env_file:
    #   - .env
